export const CREATE_TODO = 'CREATE_TODO';
export const DELETE_TODO = 'DELETE_TODO';
export const UPDATE_DONE_STATUS = 'UPDATE_DONE_STATUS';
export const ADD_TODO_LIST = 'ADD_TODO_LIST';
export const LABEL_LIST = 'LABEL_LIST';
export const CREATE_TODO_LABEL = 'CREATE_TODO_LABEL';
export const DELETE_LABEL = 'DELETE_LABEL';


